<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="sov.local" ignored="0" name="Default test" tests="8" failures="0" timestamp="27 Aug 2018 12:15:42 GMT" time="73.578" errors="0">
  <testcase name="@AfterTest closeBrowser" time="0.0" classname="com.Google.testcases.BaseScenarios">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at com.Google.testcases.BaseScenarios.closeBrowser(BaseScenarios.java:135)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.TestRunner.afterRun(TestRunner.java:983)
	at org.testng.TestRunner.run(TestRunner.java:614)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @AfterTest closeBrowser -->
  <testcase name="verifyGoogleSearchValidString" time="2.073" classname="com.Google.testcases.GoogleTestCases"/>
  <testcase name="verifyIAmFeelingLuckyLink" time="1.127" classname="com.Google.testcases.GoogleTestCases"/>
  <testcase name="verifyGoogleSearchInvalidString" time="10.832" classname="com.Google.testcases.GoogleTestCases"/>
  <testcase name="verifySearchResultsClickFirstLink" time="4.164" classname="com.Google.testcases.GoogleTestCases"/>
  <testcase name="verifyVideosTabSearchResult" time="0.441" classname="com.Google.testcases.GoogleTestCases"/>
  <testcase name="verifyImagesTabSearchResult" time="2.13" classname="com.Google.testcases.GoogleTestCases"/>
  <testcase name="verifyNewsTabSearchResult" time="1.2" classname="com.Google.testcases.GoogleTestCases"/>
  <testcase name="verifyMapsTabSearchResult" time="13.096" classname="com.Google.testcases.GoogleTestCases"/>
</testsuite> <!-- Default test -->
